project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - index.qmd
    - pages/sample.qmd
    - pages/task1.qmd
    - pages/task2.qmd
    - pages/subjective.qmd
    - pages/figures.qmd

website:
  title: "Uncertainty in topoplots"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/sample.qmd
        text: Sample
      - href: pages/task1.qmd
        text: Task 1
      - href: pages/task2.qmd
        text: Task 2
      - href: pages/subjective.qmd
        text: Subjective evaluation
      - href: pages/figures.qmd
        text: Publication figures

format:
  html:
    toc: true
    code-fold: true
    grid:
      body-width: 1200px

editor: visual
