---
title: "Subjective evaluation"
execute:
  warning: false
  message: false
params:
  export_artifacts: false
---

```{r shared-setup}
#| include: false
source("scripts/analysis_setup.R")
```


## Rating data preparation and descriptive summary

```{r}

question_labels <- c(
  A301 = "Helpful for comparison",
  A302 = "Helpful for detection and integration",
  A303 = "Helpful for representation",
  A304 = "Aesthetically appealing"
)

likert <- data %>%
  select(ID, matches("^A30[1-4]_\\d{2}$")) %>%
  pivot_longer(
    -ID,
    names_to = c("question_code", "number"),
    names_pattern = "(A30[1-4])_(\\d{2})",
    values_to = "rating_raw"
  ) %>%
  mutate(
    number = as.integer(number),

    vistype = factor(
      vistypes[number],
      levels = vistypes
    ),

    question = factor(
      question_code,
      levels = names(question_labels),
      labels = unname(question_labels)
    ),

    rating = as.integer(
      stringr::str_extract(as.character(rating_raw), "^-?\\d+")
    ),

    rating = if_else(
      rating %in% 1:5,
      rating,
      NA_integer_
    )
  ) %>%
  select(ID, question, vistype, rating)
likert
```
```{r likert-summary-table}
likert_table <- likert %>%
  group_by(vistype, question) %>%
  summarise(
    mean_rating = round(mean(rating, na.rm = TRUE), 2),
    .groups = "drop"
  ) %>%
  tidyr::pivot_wider(
    names_from = question,
    values_from = mean_rating
  ) %>% mutate(
    sum = rowSums(across(where(is.numeric)), na.rm = TRUE)
  ) %>%
  arrange(desc(sum))

likert_table
```
## Ordinal mixed-effects models

```{r}
likert_model_data <- likert |>
  filter(!is.na(rating)) |>
  mutate(
    ID = factor(ID),
    vistype = droplevels(factor(vistype)),
    rating_ord = ordered(rating, levels = 1:5)
  )

likert_models <- likert_model_data |>
  (\(data) split(data, data$question))() |>
  map(
    \(data_question) clmm(
      rating_ord ~ vistype + (1 | ID),
      data = data_question,
      Hess = TRUE
    )
  )

likert_estimates <- imap_dfr(
  likert_models,
  function(model, question_name) {

    emmeans(
      model,
      ~ vistype,
      mode = "mean.class"
    ) |>
      confint() |>
      as.data.frame() |>
      transmute(
        question = question_name,
        vistype,
        estimated_rating = mean.class,
        lower_ci = asymp.LCL,
        upper_ci = asymp.UCL
      )
  }
)

likert_estimates
```

## Model-estimated ratings

```{r}
#| fig-width: 16
#| fig-height: 11
question_columns <- unname(question_labels)

likert_vistype_order <- c(
  "basic",
  "adjacent",
  "triple_CI",
  "uncert_markers",
  "animation",
  "bivariate_range",
  "bivariate_corner"
)

likert_display_labels <- c(
  basic = "Basic topoplot",
  adjacent = "Adjacent plots",
  triple_CI = "Confidence intervals",
  uncert_markers = "Uncertainty markers",
  animation = "Animation",
  bivariate_range = "Bivariate range",
  bivariate_corner = "Bivariate corner"
)

likert_panel_titles <- c(
  "Helpful for comparison" = "Helpful for comparison",
  "Helpful for detection and integration" = "Helpful for detection & integration",
  "Helpful for representation" = "Helpful for representation",
  "Aesthetically appealing" = "Aesthetically appealing"
)

make_likert_estimate_plot <- function(
  question_name,
  show_x = TRUE,
  show_labels = TRUE
) {

  plot_data <- likert_estimates |>
    filter(question == question_name) |>
    mutate(
      colour_group = if_else(vistype == "basic", "basic", "other"),
    
      display_label = unname(
        likert_display_labels[as.character(vistype)]
      ),
    
      vistype = factor(
        vistype,
        levels = rev(likert_vistype_order)
      )
    )

  p <- ggplot(
    plot_data,
      aes(
    x = estimated_rating,
    y = vistype,
    colour = colour_group
  )
  ) +
    geom_errorbar(
      aes(
        xmin = lower_ci,
        xmax = upper_ci
      ),
      orientation = "y",
      width = 0.12,
      linewidth = 0.55
    ) +
    geom_point(size = 3) +

    # Estimated values
    geom_text(
      aes(label = sprintf("%.1f", estimated_rating)),
      nudge_y = 0.32,
      vjust = 0.5,
      size = 30 / ggplot2::.pt
    ) +

    scale_colour_manual(
  values = c(
    basic = "#3B78B4",
    other = "#222222"
  ),
  guide = "none"
) +

    scale_x_continuous(
      breaks = 1:5,
      labels = function(x) sprintf("%.0f", x),
      expand = expansion(mult = c(0.02, 0.02))
    ) +

    # Hide ordinary y-axis labels
    scale_y_discrete(
      labels = NULL,
      expand = expansion(add = 0.5)
    ) +

    # Show custom labels placed slightly outside the panel
    coord_cartesian(
      xlim = c(1, 5),
      clip = "off"
    ) +

    labs(
      title = unname(likert_panel_titles[question_name]),
      x = NULL,
      y = NULL
    ) +

    theme_classic(base_family = "Lato", base_size = 20) +

    theme(
      plot.title = element_text(
        hjust = 0.5,
        face = "bold",
        size = 50
      ),
      axis.text.x = element_text(size = 20),
      axis.title.x = element_text(size = 20),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.line.y = element_blank(),
      panel.background = element_rect(fill = "white", colour = NA),
      plot.background = element_rect(fill = "white", colour = NA),

      # Space for custom labels
       plot.margin = margin(
    t = 5.5,
    r = 5.5,
        b = 8,
    l = if (show_labels) 245 else 12
  )
    )

  if (show_labels) {
    p <- p +
      geom_text(
        data = plot_data,
        aes(
          x = 0.9,
          y = vistype,
          label = display_label,
          colour = colour_group
        ),
        inherit.aes = FALSE,
        hjust = 1,
        size = 14,
        lineheight = 1
      )
  }

  if (!show_x) {
    p <- p +
      theme(
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()
      )
  }

  p
}

p1 <- make_likert_estimate_plot(
  question_columns[1],
  show_x = FALSE
)

p2 <- make_likert_estimate_plot(
  question_columns[2],
  show_x = FALSE,
  show_labels = FALSE
)

p3 <- make_likert_estimate_plot(
  question_columns[3],
  show_x = TRUE
)

p4 <- make_likert_estimate_plot(
  question_columns[4],
  show_x = TRUE,
  show_labels = FALSE
)

likert_estimate_figure <-
  (p1 + p2) /
  (p3 + p4) +
  plot_annotation(
    caption = "Expected rating",
    theme = theme(
      plot.caption = element_text(
        hjust = 0.5,
        size = 26,
        family = "Lato",
        lineheight = 1.1,
        margin = margin(t = 10, b = 6)
      ),
      plot.caption.position = "plot",
      plot.margin = margin(6, 12, 12, 12)
    )
  )


likert_estimate_figure

ggsave(
  project_path("figures", "likert_estimate_figure.png"),
  likert_estimate_figure,
  width = 16,
  height = 11,
  dpi = 180
)
```

## Differences relative to Basic topoplot

```{r likert-basic-contrasts}
#| include: false

likert_contrasts <- imap_dfr(
  likert_models,
  function(model, question_name) {
    question_emmeans <- emmeans(
      model,
      ~ vistype,
      mode = "mean.class"
    )

    basic_reference <- which(
      question_emmeans@levels$vistype == "basic"
    )

    contrast_result <- contrast(
      question_emmeans,
      method = "trt.vs.ctrl",
      ref = basic_reference
    ) |>
      confint() |>
      as.data.frame()

    lower_column <- grep(
      "lower.CL$|asymp.LCL$",
      names(contrast_result),
      value = TRUE
    )[1]
    upper_column <- grep(
      "upper.CL$|asymp.UCL$",
      names(contrast_result),
      value = TRUE
    )[1]

    contrast_result |>
      transmute(
        question = question_name,
        vistype = stringr::str_remove(contrast, " - basic$"),
        difference = estimate,
        lower_ci = .data[[lower_column]],
        upper_ci = .data[[upper_column]]
      )
  }
) |>
  group_by(question) |>
  mutate(
    vistype = factor(vistype, levels = rev(likert_vistype_order[-1])),
    is_leader = difference == max(difference, na.rm = TRUE)
  ) |>
  ungroup()

likert_contrast_limit <- max(
  2,
  ceiling(
    max(abs(c(likert_contrasts$lower_ci, likert_contrasts$upper_ci)), na.rm = TRUE) * 10
  ) / 10
)

format_rating_difference <- function(x) {
  ifelse(
    abs(x) < 0.05,
    "0.0",
    sprintf("%+.1f", x)
  )
}

make_likert_contrast_plot <- function(
  question_name,
  show_x = TRUE,
  show_labels = TRUE
) {
  plot_data <- likert_contrasts |>
    filter(question == question_name)

  p <- ggplot(
    plot_data,
    aes(x = difference, y = vistype)
  ) +
    geom_vline(
      xintercept = 0,
      linetype = "dashed",
      linewidth = 0.6,
      colour = "#3B78B4"
    ) +
    geom_errorbar(
      aes(xmin = lower_ci, xmax = upper_ci, colour = is_leader),
      orientation = "y",
      width = 0.12,
      linewidth = 0.55
    ) +
    geom_point(aes(colour = is_leader), size = 3) +
    geom_text(
      aes(
        label = format_rating_difference(difference),
        colour = is_leader
      ),
      nudge_y = 0.3,
      vjust = 0.5,
      size = 30 / ggplot2::.pt
    ) +
    scale_colour_manual(
      values = c(`FALSE` = "#222222", `TRUE` = "#D94B5B"),
      guide = "none"
    ) +
    scale_y_discrete(
      labels = function(x) unname(likert_display_labels[x]),
      expand = expansion(add = 0.5)
    ) +
    scale_x_continuous(
      breaks = -2:2,
      labels = function(x) format_rating_difference(x),
      expand = expansion(mult = 0.04)
    ) +
    coord_cartesian(
      xlim = c(-likert_contrast_limit, likert_contrast_limit),
      clip = "on"
    ) +
    labs(
      title = unname(likert_panel_titles[question_name]),
      x = NULL,
      y = NULL
    ) +
    theme_classic(base_family = "Lato", base_size = 20) +
    theme(
      plot.title = element_text(
        hjust = 0.5,
        face = "bold",
        size = 50
      ),
      axis.text.x = element_text(size = 20),
      axis.text.y = element_text(size = 40, margin = margin(r = 12)),
      axis.ticks.y = element_blank(),
      axis.line.y = element_blank(),
      panel.background = element_rect(fill = "white", colour = NA),
      plot.background = element_rect(fill = "white", colour = NA),
      plot.margin = margin(6, 12, 8, 12)
    )

  if (!show_x) {
    p <- p +
      theme(
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()
      )
  }

  if (!show_labels) {
    p <- p +
      theme(axis.text.y = element_blank())
  }

  p
}
```

```{r likert-basic-contrast-figure}
#| fig-width: 16
#| fig-height: 11

contrast_p1 <- make_likert_contrast_plot(question_columns[1], show_x = FALSE)
contrast_p2 <- make_likert_contrast_plot(
  question_columns[2],
  show_x = FALSE,
  show_labels = FALSE
)
contrast_p3 <- make_likert_contrast_plot(question_columns[3], show_x = TRUE)
contrast_p4 <- make_likert_contrast_plot(
  question_columns[4],
  show_x = TRUE,
  show_labels = FALSE
)

likert_contrast_caption <- ggplot() +
  annotate(
    "text",
    x = 0.587,
    y = 0.5,
    label = "Difference in model-estimated expected rating vs",
    hjust = 1,
    size = 50 / ggplot2::.pt,
    family = "Lato",
    colour = "#222222"
  ) +
  annotate(
    "text",
    x = 0.593,
    y = 0.5,
    label = "Basic topoplot",
    hjust = 0,
    size = 50 / ggplot2::.pt,
    family = "Lato",
    colour = "#377EB8"
  ) +
  coord_cartesian(xlim = c(0, 1), ylim = c(0, 1), clip = "off") +
  theme_void()

likert_contrast_figure <-
  ((contrast_p1 + contrast_p2) /
    (contrast_p3 + contrast_p4) /
    likert_contrast_caption) +
  plot_layout(heights = c(1, 1, 0.16)) &
  theme(plot.margin = margin(6, 12, 6, 12))

likert_contrast_figure

ggsave(
  project_path("figures", "likert_contrast_figure.png"),
  likert_contrast_figure,
  width = 16,
  height = 11,
  dpi = 180
)
```


```{r}
likert_estimates |>
  mutate(
    ci_width = upper_ci - lower_ci,
    lower_half = estimated_rating - lower_ci,
    upper_half = upper_ci - estimated_rating
  ) |>
  arrange(question, vistype) |>
  select(
    question,
    vistype,
    estimated_rating,
    lower_ci,
    upper_ci,
    ci_width,
    lower_half,
    upper_half
  )
```
